version: '3.8'

services:
  nginx:
    container_name: api-gateway
    image: jonepl/api-gateway:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .local.env:/run/secrets/shared_secret
    networks:
      - portfolio-network
    entrypoint: ["/bin/bash", "/etc/nginx/entrypoint.sh"]

networks:
  portfolio-network:
    external: false
