name: CI

on:
  push:
    branches: 
      - "main" 
      - "**"
  pull_request:
    branches: 
      - main

jobs:
  compare-versions:
    name: Check Image Version Incremented
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Version
        run: |
          # Fetch the current version from the VERSION file
          current_version=$(cat VERSION)

          # Fetch the previous semantic version (excluding 'latest') from Docker images
          previous_version=$(docker image ls --filter "reference=jonepl/api-gateway" --format "{{.Repository}}:{{.Tag}}" | awk -F ':' '{print $2}' | grep -v 'latest' | sort -rV | head -n 1)

          # Function to compare semantic versions
          version_greater() {
              IFS='.' read -r -a current_parts <<< "$1"
              IFS='.' read -r -a previous_parts <<< "$2"

              for ((i=0; i<${#current_parts[@]}; i++)); do
                  if [[ ${current_parts[$i]} -gt ${previous_parts[$i]} ]]; then
                      return 0
                  elif [[ ${current_parts[$i]} -lt ${previous_parts[$i]} ]]; then
                      return 1
                  fi
              done

              return 1
          }

          # Compare the current and previous versions
          if version_greater "$current_version" "$previous_version"; then
              echo "The version has been properly incremented: $previous_version -> $current_version"
          else
              echo "Error: The version has not been incremented properly: $previous_version -> $current_version"
              exit 1
          fi

  tests:
    name: Runs Tests
    runs-on: ubuntu-latest
    needs: [ "compare-versions" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # - name: Setup Bats and bats libs
      #   id: setup-bats
      #   uses: bats-core/bats-action@3.0.0

      - name: Start Docker Network
        run: docker network create test-network
    
      - name: Start Test Container
        run: |
          docker build -f tests/test.dockerfile -t api-gateway-test .
          docker run -dp 8080:80 --name api-gateway-test -v ${{ github.workspace }}/tests/test.env:/run/secrets/app_config api-gateway-test

      - name: Verify Container is Running
        run: |
          # Check if container is running
          for i in {1..10}; do
            echo "Checking if the container 'api-gateway-test' is running (attempt $i)..."
            if docker ps --filter "name=api-gateway-test" --filter "status=running" | grep -q api-gateway-test; then
              echo "Container 'api-gateway-test' is running."
              exit 0
            fi
            echo "Container 'api-gateway-test' is not running yet. Sleeping for 2 seconds..."
            sleep 2
          done
          echo "Container 'api-gateway-test' did not start in time."
          exit 1

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [ "compare-versions" ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          current_version=$(cat VERSION)
          docker build -t jonepl/api-gateway:$current_version -t jonepl/api-gateway:latest .
          docker save --output versioned.docker jonepl/api-gateway:$current_version
          docker save --output latest.docker jonepl/api-gateway:latest

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            versioned.docker
            latest.docker

  push-docker-image:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: docker-images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker load --input ./versioned.docker
          docker load --input ./latest.docker
          current_version=$(cat VERSION)
          docker push jonepl/api-gateway:$current_version
          docker push jonepl/api-gateway:latest

  deploy-docker-compose:
    name: Deploy Docker Compose
    runs-on: ubuntu-latest
    needs: push-docker-image
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Ensure SSH key is available
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check SSH connection
        run: ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} 'echo "SSH connection successful"'

      - name: Copy Docker Compose file to remote server
        run: |
          ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hostsz
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/api-gateway/docker-compose.yml

      - name: Update Docker Swarm service
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          'docker stack deploy -c /srv/app/api-gateway/docker-compose.yml hosted-apps || echo "Deployment failed with error $?"'
